export const FETCH_FRIENDS = 'FETCH_FRIENDS'
export const FETCH_FRIENDS_PENDING = 'FETCH_FRIENDS_PENDING'
export const FETCH_FRIENDS_FULFILLED = 'FETCH_FRIENDS_FULFILLED'
export const FETCH_FRIENDS_REJECTED = 'FETCH_FRIENDS_REJECTED'
export const ADD_FRIEND = 'ADD_FRIEND';
